<?php

/**
 * @file
 * Install file for MojoCart demo.
 */

/**
 * Implements hook_enable().
 */
function mojocart_demo_enable() {
  _panopoly_core_import_demo_content(array('MojoCartDemoProducts', 'MojoCartDemoProductDisplays', 'MojoCartDemoMenu'));
}

/**
 * Implements hook_disable().
 */
function mojocart_demo_disable() {
  _panopoly_core_rollback_demo_content(array('MojoCartDemoProducts', 'MojoCartDemoProductDisplays', 'MojoCartDemoMenu'));
}
